---
sudo: required
language: python
services: docker

env:
  - version=">=2.7,<2.8" distro="alpine-latest" expectation="fail"
  - version="" distro="alpine-latest" expectation="fail"
  - version="devel" distro="alpine-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
  - version="" distro="alpine-edge" expectation="fail"
  - version="devel" distro="alpine-edge" expectation="fail"
  - version=">=2.7,<2.8" distro="archlinux" expectation="fail"
  - version="" distro="archlinux" expectation="fail"
  - version="devel" distro="archlinux" expectation="fail"
  - version=">=2.7,<2.8" distro="centos-7"
  - version="" distro="centos-7"
  - version="devel" distro="centos-7"
  - version=">=2.7,<2.8" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.7,<2.8" distro="debian-stable" expectation="fail"
  - version="" distro="debian-stable" expectation="fail"
  - version="devel" distro="debian-stable" expectation="fail"
  - version=">=2.7,<2.8" distro="debian-unstable" expectation="fail"
  - version="" distro="debian-unstable" expectation="fail"
  - version="devel" distro="debian-unstable" expectation="fail"
  - version=">=2.7,<2.8" distro="fedora-latest"
  - version="" distro="fedora-latest"
  - version="devel" distro="fedora-latest"
  - version=">=2.7,<2.8" distro="fedora-rawhide"
  - version="" distro="fedora-rawhide"
  - version="devel" distro="fedora-rawhide"
  - version=">=2.7,<2.8" distro="opensuse-leap" expectation="fail"
  - version="" distro="opensuse-leap" expectation="fail"
  - version="devel" distro="opensuse-leap" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-rolling" expectation="fail"
  - version="" distro="ubuntu-rolling" expectation="fail"
  - version="devel" distro="ubuntu-rolling" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-latest" expectation="fail"
  - version="" distro="ubuntu-latest" expectation="fail"
  - version="devel" distro="ubuntu-latest" expectation="fail"
  - version=">=2.7,<2.8" distro="ubuntu-devel" expectation="fail"
  - version="" distro="ubuntu-devel" expectation="fail"
  - version="devel" distro="ubuntu-devel" expectation="fail"

matrix:
  allow_failures:
    - env: version=">=2.7,<2.8" distro="alpine-edge" expectation="fail"
    - env: version="" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-latest" expectation="fail"
    - env: version="devel" distro="archlinux" expectation="fail"
    - env: version="devel" distro="centos-7"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-stable" expectation="fail"
    - env: version=">=2.7,<2.8" distro="debian-unstable" expectation="fail"
    - env: version="" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="fedora-latest"
    - env: version=">=2.7,<2.8" distro="fedora-rawhide"
    - env: version="" distro="fedora-rawhide"
    - env: version="devel" distro="fedora-rawhide"
    - env: version="devel" distro="opensuse-leap" expectation="fail"
    - env: version="devel" distro="ubuntu-rolling" expectation="fail"
    - env: version=">=2.7,<2.8" distro="ubuntu-devel" expectation="fail"
    - env: version="" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-latest" expectation="fail"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "DU8pajNrHhXuhVaFNcZQ7T0CPL86CUd/ysJeyAwjt/rEWffy2mNp+bSjc1VmJG3qfypcwJHLh+z12MdYX4DFoPqmbkaC9avPirVGtMAUfsnX+CU8Aii9WESjL+qaCS0gGfQK0jIZE7/Z5sFlJleelxd0Pdkkrm7NcYAgZtPiWzefJgLNXIEUMgzdbROITPzb6+GirsTdc+XqmVWvJg/SV+Vm4RuDaNREX8pPfmEE6M2+vXprISRuTqF/1CG3Z6DpgJBjQtvld2N32qCFqadrY6RFbDlQ8t2ctIMhauF9bx9/0oiu3NCIXmKwtD8XGMkIRwQzwteAf8ikKkOn8SM7B3LtQjHlSRecrsdOLP3kWc5JadDuEDndsp99Yo192evUtrY14NqT4Y9AOKjzXB76aRHRJx//F7LtapqJlBBduCzcsSgMqLghvrCEHxo+CIF/A729ZHQtL2n/l9Jh5AOytj666rg47M5AIGWSMrYgAF01gBwHKKLBBm6BEo4UR2KT5c/OlKx/h9vSVgCTuLy5snZluiXNh8GP1ne1s4MdASmAyRU0rJJmeV2PRRT5jZegv65A4HrhepYOlvcjjNpY/fea+y279r4d9yWkZsXqQgZjGDdTCa9wLRmeNp35p00Em2uaw2h+Yy8uq+8cWUFOA+GY9o/D4ZBkwhPWn6Jrw+0="
  email: false
