---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - secure: "qEAaYGYZ1fqowDmDkRxk59aB/O01Rp3itUtpBJLoSpYphmtKyPeWuB32U4D09eT7kuyLQWMyE6gSSzZbpPEcfolNsNd3+0QKBLxmLvT8jrj6BhVX2y4upthUMs2tWYzu9UzwEeCH/OGQydzItDQJjgDCqh+42+9ZFQDuBiXaZ+Qw7+E1n/N4EILDlKIeNiugtd+Vpl9azqXjFkVA2vujsbymGZTaQcsNfZ8Dq2Afl/oU17NoAFioa0rETe9oXA6SUbCLhDvwN98Sc0iyu67WaMa7oY+tTt2wbLd7GrU95eyiEmGUqMn4jPaFcIN0EBa/zeBlaclPmfkJBO2NjRS4iLRWVlN4iGjx0Yu5M1i6LDdnc2kOuH969+tyKV6OZUXyQw9XFeqVSMNAjGWXql9SR8YJGijXKBOP54UvXFfOciR2D+5T6X3rzvSOclLBtyDstZsYup7ewCiRkuFNDq3Fm4hX5Eh0s1cjwMqstSINQWBo05CpbGicoKe/CIwaR53R2dhIhkP76YfQxfcgBKRSTuMO2yd559xPsjy+t9harK6NrQEoK1mHtU0BtIi1rJzvN6CuwZwUP9OHEeyze3OCuUlBSz95MYdc8w+fxYyBvYMEQiY8iNBkRCHnhjxQYY1ZJ9H7sbdW22FHCxHTtTctceR9IYY4rJRYmK6Po2svBow="
  email: false
