---
# tasks file for digitalocean-agent
- name: import rpm key
  rpm_key:
    key: "{{ digitalocean_agent_gpgkey }}"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: import apt key
  apt_key:
    url: "{{ digitalocean_agent_gpgkey }}"
  when:
    - ansible_pkg_mgr == "apt"

- name: install repository (yum)
  copy:
    src: digitalocean-agent.repo
    dest: /etc/yum.repos.d/digitalocean-agent.repo
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: install repository (apt)
  copy:
    src: digitalocean-agent.list
    dest: /etc/apt/sources.list.d/digitalocean-agent.list
  when:
    - ansible_pkg_mgr == "apt"
  notify:
    - update apt cache

- name: flush handlers
  meta: flush_handlers

- name: install software
  package:
    name: do-agent
