---
# tasks file for digitalocean-agent
- name: import rpm key
  rpm_key:
    key: "{{ digitalocean_agent_gpgkey }}"
  when:
    - ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: import apt key
  apt_key:
    url: "{{ digitalocean_agent_gpgkey }}"
    validate_certs: "{{ digitalocean_agent_validate_certs }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install repository
  copy:
    src: "{{ digitalocean_agent_repository_src }}"
    dest: "{{ digitalocean_agent_repository_dest }}"
    mode: "0640"
  when:
    - ansible_pkg_mgr in ["yum", "dnf", "apt"]
  notify:
    - update apt cache

- name: flush handlers
  meta: flush_handlers

- name: install do-agent
  package:
    name: do-agent
    state: present

- name: start do-agent
  service:
    name: do-agent
    state: started
    enabled: yes
