---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: digitalocean-agent-debian
    box: debian/stretch64
  - name: digitalocean-agent-fedora
    box: fedora/29-cloud-base
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
