---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: check /opt/digitalocean/bin/do-agent
      stat:
        path: /opt/digitalocean/bin/do-agent
      register: check_do_agent

    - name: collect service_facts
      service_facts:
      register: service_facts

    - name: check conditions
      assert:
        that:
          - check_do_agent.stat.exists
          - check_do_agent.stat.executable
          - services['do-agent.service'].state == "running"
          - services['do-agent.service'].status == "enabled"
