---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: check /opt/digitalocean/bin/do-agent
      stat:
        path: /opt/digitalocean/bin/do-agent
      register: check_do_agent

    - name: check conditions
      assert:
        that:
          - check_do_agent.stat.exists
          - check_do_agent.stat.executable
